// Load modules.
const OAuth2Strategy = require('passport-oauth2')
  , util = require('util')
  , InternalOAuthError = require('passport-oauth2').InternalOAuthError
  , { v4: uuidv4 } = require('uuid');


/**
 * `Strategy` constructor.
 *
 * The Square authentication strategy authenticates requests by delegating to
 * Square using the OAuth 2.0 protocol.
 *
 * Applications must supply a `verify` callback which accepts an `accessToken`,
 * `refreshToken` and service-specific `profile`, and then calls the `done`
 * callback supplying a `user`, which should be set to `false` if the
 * credentials are not valid.  If an exception occured, `err` should be set.
 *
 * Options:
 *   - `clientId`      	Mandatory. Your Square application's client id
 *   - `clientSecret`  	Mandatory. Your Square application's client secret
 *   - `callbackURL`   	Mandatory. URL to which Square will redirect the user after granting authorization
 *   - `grantType`		Optional. Must be authorization_code.
 *   - `isLive`         Optional. Whether to use Square's live environment or not. Default is false.
 *   - `scope`          Optional. Scope. Default is MERCHANT_PROFILE_READ.
 *   - `stateFunc`      Optional. Pass a function that can generate state param. Defaults to a value generated by uuidv4
 *
 * Examples:
 *
 *     passport.use(new SquareStrategy({
 *         clientId: '123-456-789',
 *         clientSecret: 'shhh-its-a-secret'
 *         callbackURL: 'https://www.example.net/auth/Square/callback'
 *       },
 *       function(accessToken, refreshToken, profile, done) {
 *         User.findOrCreate(..., function (err, user) {
 *           done(err, user);
 *         });
 *       }
 *     ));
 *
 * @param {Object} options
 * @param {Function} verify
 * @api public
 */
function Strategy(options, verify) {
  options = Object.assign({}, options);
  options.isLive = options.isLive || false;
  const squareupHost = 'https://connect.squareup' + (options.isLive ? '' : 'sandbox') + '.com';
  //https://developer.squareup.com/docs/oauth-api/how-oauth-works
  options.authorizationURL = options.authorizationURL || (squareupHost + '/oauth2/authorize');
  options.tokenURL = options.tokenURL || (squareupHost + '/oauth2/token');
  options.profileURL = options.profileURL || (squareupHost + '/v2/merchants/me');
  options.scope = options.scope || 'MERCHANT_PROFILE_READ';
  options.scopeSeparator = options.scopeSeparator || ',';
  options.grant_type = options.grantType || 'authorization_code';
  options.stateFunc = options.stateFunc || uuidv4;

  OAuth2Strategy.call(this, options, verify);
  this.name = 'square';
  this.options = options;
}

// Inherit from `OAuth2Strategy`.
util.inherits(Strategy, OAuth2Strategy);



/**
 * Retrieve user profile from Square.
 *
 * This function constructs a normalized profile, with the following properties:
 *
 *   - `provider`         always set to `square`
 *   - `id`
 *   - `displayName`
 *   - `businessName`
 *   - `mainLocationId`
 *
 * @param {String} accessToken
 * @param {Function} done
 * @api protected
 */
Strategy.prototype.userProfile = function(accessToken, done) {
  const self = this;
  const authorization = 'Bearer ' + accessToken;
  const headers = {
    'Authorization' : authorization
  };
  this._oauth2._request('GET', this.options.profileURL, headers, '', '', function(err, body, res) {
    if (err) {
      return done(new InternalOAuthError('failed to fetch user profile', err));
    }

    try {
      const squareMerchant = JSON.parse(body).merchant;
      const profile = {
        provider: 'square',
        id: squareMerchant.id,
        displayName: squareMerchant.business_name,
        //email : squareMerchant.email,
        businessName: squareMerchant.business_name,
        mainLocationId: squareMerchant.main_location_id,
        _squareProfile: squareMerchant
      };
      profile._rawBody = body;
      profile._jsonBody = JSON.parse(body);

      done(null, profile);
    } catch (e) {
      done(e);
    }
  });
};

/**
 * Return any extra Square-specific parameters to be included in the authorization
 * request.
 *
 * @param {object} options
 * @return {object}
 * @access protected
 */
Strategy.prototype.authorizationParams = function(options) {
  const params = {};
  if (this.options.stateFunc && typeof this.options.stateFunc === 'function') {
    params.state = this.options.stateFunc();
  } else {
    params.state = uuidv4();
  }
  return params;
}


/**
 * Expose `Strategy`.
 */
module.exports = Strategy;
